// ============================================
// Flat monochrome SVG icons - Kadix
// Uses Lucide React icons for all products & categories
// ============================================

import {
  Apple,
  Banana,
  Cherry,
  Citrus,
  Carrot,
  Leaf,
  Sprout,
  Croissant,
  Milk,
  Egg,
  Drumstick,
  Fish,
  Wheat,
  Cookie,
  Candy,
  Cake,
  IceCream,
  Wine,
  Beer,
  CupSoda,
  Coffee,
  Snowflake,
  SprayCan,
  Shirt,
  Trash2,
  Heart,
  Pill,
  Dog,
  Cat,
  Package,
  ShoppingBag,
  Box,
  Star,
  UtensilsCrossed,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icon registry: maps icon names to Lucide components.
 * Allows components to look up icons by string name.
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  // Categories
  Apple,
  Banana,
  Cherry,
  Citrus,
  Carrot,
  Leaf,
  Sprout,
  Croissant,
  Milk,
  Egg,
  Drumstick,
  Fish,
  Wheat,
  Cookie,
  Candy,
  Cake,
  IceCream,
  Wine,
  Beer,
  CupSoda,
  Coffee,
  Snowflake,
  SprayCan,
  Shirt,
  Trash2,
  Heart,
  Pill,
  Dog,
  Cat,
  Package,
  ShoppingBag,
  Box,
  Star,
  UtensilsCrossed,
};

/** Fallback icon when nothing matches */
export const FALLBACK_ICON: LucideIcon = Package;

/**
 * Resolve an icon by name, returning the Lucide component.
 */
export function getIcon(name: string): LucideIcon {
  return ICON_REGISTRY[name] ?? FALLBACK_ICON;
}

// ============================================
// Category Icons
// Each category gets a flat monochrome Lucide icon
// ============================================

export const CATEGORY_ICONS: Record<string, string> = {
  'Fruits & Légumes': 'Apple',
  'Pains & Pâtisseries': 'Croissant',
  'Produits Laitiers': 'Milk',
  'Viandes & Poissons': 'Drumstick',
  'Ingrédients & Épices': 'Sprout',
  'Surgelés & Plats Cuisinés': 'Snowflake',
  'Pâtes, Riz & Céréales': 'Wheat',
  'Snacks & Friandises': 'Cookie',
  'Boissons': 'Wine',
  'Foyer': 'SprayCan',
  'Soin & Santé': 'Heart',
  'Animaux': 'Dog',
  'Autre': 'Package',
};

/** Get the Lucide icon component for a category */
export function getCategoryIcon(category: string): LucideIcon {
  const iconName = CATEGORY_ICONS[category];
  return iconName ? getIcon(iconName) : FALLBACK_ICON;
}

// ============================================
// Product Icons
// Mappings for specific products to flat monochrome Lucide icons
// Products not listed fall back to their category icon
// ============================================

export const PRODUCT_ICONS: Record<string, string> = {
  // ── Fruits & Légumes ──
  'Pommes': 'Apple',
  'Bananes': 'Banana',
  'Oranges': 'Citrus',
  'Citrons': 'Citrus',
  'Cerises': 'Cherry',
  'Raisins': 'Cherry',
  'Myrtilles': 'Cherry',
  'Framboises': 'Cherry',
  'Frais': 'Cherry',
  'Fraises': 'Cherry',
  'Carottes': 'Carrot',
  'Salade verte': 'Leaf',
  'Salade': 'Leaf',
  'Épinards': 'Leaf',
  'Mâche': 'Leaf',
  'Roquette': 'Leaf',
  'Basilic': 'Leaf',
  'Menthe': 'Leaf',
  'Persil': 'Leaf',
  'Ciboulette': 'Leaf',
  'Aneth': 'Leaf',
  'Coriandre': 'Leaf',
  'Estragon': 'Leaf',
  'Sauge': 'Leaf',
  'Laurier': 'Leaf',
  'Thym': 'Leaf',
  'Romarin': 'Leaf',
  'Origan': 'Leaf',
  'Ail': 'Sprout',
  'Oignons': 'Sprout',
  'Échalotes': 'Sprout',
  'Poireaux': 'Sprout',
  'Asperges': 'Sprout',
  'Brocolis': 'Sprout',
  'Chou-fleur': 'Sprout',
  'Choux': 'Leaf',
  'Chou': 'Leaf',

  // ── Pains & Pâtisseries ──
  'Baguette': 'Croissant',
  'Pain de campagne': 'Croissant',
  'Pain complet': 'Croissant',
  'Pain de mie': 'Croissant',
  'Pain burger': 'Croissant',
  'Pain pita': 'Croissant',
  'Pain au lait': 'Croissant',
  'Pain suédois': 'Croissant',
  'Brioche': 'Croissant',
  'Croissants': 'Croissant',
  'Croissant': 'Croissant',
  'Pains au chocolat': 'Croissant',
  'Pain aux raisins': 'Croissant',
  'Viennoiseries': 'Croissant',
  'Cookies': 'Cookie',
  'Muffins': 'Cake',
  'Madeleines': 'Cake',
  'Crêpes': 'Cake',
  'Gauffres': 'Cake',

  // ── Produits Laitiers ──
  'Lait demi-écrémé': 'Milk',
  'Lait entier': 'Milk',
  'Lait écrémé': 'Milk',
  'Lait': 'Milk',
  'Beurre': 'Milk',
  'Œufs': 'Egg',
  'Œuf': 'Egg',
  'Fromage râpé': 'Milk',
  'Mozzarella': 'Milk',
  'Parmesan': 'Milk',
  'Comté': 'Milk',
  'Emmental': 'Milk',
  'Camembert': 'Milk',
  'Brie': 'Milk',
  'Chèvre': 'Milk',
  'Roquefort': 'Milk',
  'Fromage blanc': 'Milk',
  'Yaourt nature': 'Milk',
  'Yaourt fruit': 'Milk',
  'Yaourt grec': 'Milk',
  'Yaourt': 'Milk',
  'Crème fraîche': 'Milk',
  'Crème liquide': 'Milk',

  // ── Viandes & Poissons ──
  'Blanc de poulet': 'Drumstick',
  'Cuisses de poulet': 'Drumstick',
  'Poulet': 'Drumstick',
  'Steak haché': 'Drumstick',
  'Entrecôte': 'Drumstick',
  'Rôti de porc': 'Drumstick',
  'Filet mignon': 'Drumstick',
  'Rôti de bœuf': 'Drumstick',
  'Jambon blanc': 'Drumstick',
  'Jambon cru': 'Drumstick',
  'Lardons': 'Drumstick',
  'Merguez': 'Drumstick',
  'Saucisses': 'Drumstick',
  'Saumon': 'Fish',
  'Cabillaud': 'Fish',
  'Truite': 'Fish',
  'Thon frais': 'Fish',
  'Poisson pané': 'Fish',
  'Crevettes': 'Fish',
  'Gambas': 'Fish',
  'Moules': 'Fish',

  // ── Ingrédients & Épices ──
  'Sel': 'Sprout',
  'Sel fin': 'Sprout',
  'Gros sel': 'Sprout',
  'Poivre': 'Sprout',
  'Poivre noir': 'Sprout',
  'Épices': 'Sprout',
  'Curry': 'Sprout',
  'Paprika': 'Sprout',
  'Cumin': 'Sprout',
  'Cannelle': 'Sprout',
  'Muscade': 'Sprout',
  'Gingembre': 'Sprout',
  'Piment': 'Sprout',
  'Huile d\'olive': 'Sprout',
  'Huile de tournesol': 'Sprout',
  'Huile de sésame': 'Sprout',
  'Huile de coco': 'Sprout',
  'Vinaigre': 'Sprout',
  'Vinaigre balsamique': 'Sprout',
  'Sauce soja': 'Sprout',
  'Moutarde': 'Sprout',
  'Mayonnaise': 'Sprout',
  'Ketchup': 'Sprout',
  'Miel': 'Candy',
  'Sirop d\'érable': 'Candy',
  'Bouillon cube': 'UtensilsCrossed',
  'Levure': 'Wheat',
  'Farine': 'Wheat',
  'Farine de blé': 'Wheat',
  'Sucre': 'Candy',

  // ── Surgelés & Plats Cuisinés ──
  'Glace vanille': 'IceCream',
  'Glace chocolat': 'IceCream',
  'Glace fraise': 'IceCream',
  'Glace': 'IceCream',
  'Sorbet': 'IceCream',
  'Pizza surgelée': 'UtensilsCrossed',
  'Pizza': 'UtensilsCrossed',
  'Lasagnes': 'UtensilsCrossed',
  'Lasagnes surgelées': 'UtensilsCrossed',
  'Plat préparé': 'UtensilsCrossed',
  'Plats préparés surgelés': 'UtensilsCrossed',
  'Soupe': 'UtensilsCrossed',
  'Soupe fraîche': 'UtensilsCrossed',
  'Soupe en brique': 'UtensilsCrossed',
  'Frites': 'Wheat',
  'Frites surgelées': 'Wheat',
  'Purée': 'Wheat',
  'Purée en flocons': 'Wheat',

  // ── Pâtes, Riz & Céréales ──
  'Pâtes': 'Wheat',
  'Pâtes spaghetti': 'Wheat',
  'Pâtes penne': 'Wheat',
  'Pâtes fusilli': 'Wheat',
  'Pâtes tagliatelle': 'Wheat',
  'Pâtes coquillettes': 'Wheat',
  'Spaghetti': 'Wheat',
  'Riz': 'Wheat',
  'Riz blanc': 'Wheat',
  'Riz complet': 'Wheat',
  'Riz basmati': 'Wheat',
  'Quinoa': 'Wheat',
  'Semoule': 'Wheat',
  'Couscous': 'Wheat',
  'Lentilles': 'Sprout',
  'Lentilles vertes': 'Sprout',
  'Lentilles corail': 'Sprout',
  'Pois chiches': 'Sprout',
  'Haricots rouges': 'Sprout',
  'Haricots blancs': 'Sprout',
  'Céréales': 'Wheat',
  'Flocons d\'avoine': 'Wheat',
  'Avoine': 'Wheat',
  'Muesli': 'Wheat',
  'Granola': 'Wheat',

  // ── Snacks & Friandises ──
  'Chocolat noir': 'Candy',
  'Chocolat au lait': 'Candy',
  'Chocolat blanc': 'Candy',
  'Chocolat': 'Candy',
  'Nutella': 'Candy',
  'Pâte à tartiner': 'Candy',
  'Barre chocolatée': 'Candy',
  'Bonbons': 'Candy',
  'Biscuits': 'Cookie',
  'Gâteaux': 'Cake',
  'Brownie': 'Cake',
  'Barres protéinées': 'Candy',
  'Compote': 'Star',
  'Confiture': 'Star',
  'Marmelade': 'Star',
  'Cacahuètes': 'Cookie',
  'Amandes': 'Cookie',
  'Noix': 'Cookie',
  'Noisettes': 'Cookie',
  'Pistaches': 'Cookie',
  'Chips': 'Cookie',
  'Fruits secs': 'Cookie',
  'Popcorn': 'Cookie',

  // ── Boissons ──
  'Eau plate': 'CupSoda',
  'Eau gazeuse': 'CupSoda',
  'Eau minérale': 'CupSoda',
  'Eau': 'CupSoda',
  'Jus d\'orange': 'CupSoda',
  'Jus de pomme': 'CupSoda',
  'Jus': 'CupSoda',
  'Soda': 'CupSoda',
  'Coca-Cola': 'CupSoda',
  'Limonade': 'CupSoda',
  'Ice tea': 'CupSoda',
  'Café moulu': 'Coffee',
  'Café': 'Coffee',
  'Thé': 'Coffee',
  'Thé noir': 'Coffee',
  'Thé vert': 'Coffee',
  'Infusions': 'Coffee',
  'Tisane': 'Coffee',
  'Cacao': 'Coffee',
  'Chocolat chaud': 'Coffee',
  'Vin rouge': 'Wine',
  'Vin blanc': 'Wine',
  'Vin rosé': 'Wine',
  'Vin': 'Wine',
  'Bière': 'Beer',
  'Bière blonde': 'Beer',
  'Bière brune': 'Beer',
  'Cidre': 'Wine',
  'Sirop': 'CupSoda',
  'Sirop de grenadine': 'CupSoda',

  // ── Foyer ──
  'Liquide vaisselle': 'SprayCan',
  'Lessive': 'SprayCan',
  'Adoucissant': 'SprayCan',
  'Nettoyant surfaces': 'SprayCan',
  'Nettoyant vitres': 'SprayCan',
  'Nettoyant multi-surfaces': 'SprayCan',
  'Nettoyant salle de bain': 'SprayCan',
  'Nettoyant WC': 'SprayCan',
  'Désinfectant': 'SprayCan',
  'Javel': 'SprayCan',
  'Sac poubelle': 'Trash2',
  'Sac congélation': 'Box',
  'Film alimentaire': 'Box',
  'Papier aluminium': 'Box',
  'Papier cuisson': 'Box',
  'Essuie-tout': 'Shirt',
  'Papier toilette': 'Shirt',
  'Mouchoirs': 'Box',
  'Éponge': 'Shirt',
  'Chiffon': 'Shirt',
  'Piles': 'Box',
  'Ampoule': 'Star',
  'Bougie': 'Star',
  'Ciseaux': 'Trash2',
  'Ruban adhésif': 'Box',

  // ── Soin & Santé ──
  'Savon liquide': 'Heart',
  'Savon': 'Heart',
  'Gel douche': 'Heart',
  'Shampoing': 'Heart',
  'Après-shampoing': 'Heart',
  'Dentifrice': 'Heart',
  'Brosse à dents': 'Heart',
  'Déodorant': 'Heart',
  'Parfum': 'Heart',
  'Crème hydratante': 'Heart',
  'Crème solaire': 'Heart',
  'Rasoir': 'Pill',
  'Mousse à raser': 'Heart',
  'Cotons': 'Box',
  'Coton-tige': 'Pill',
  'Lingettes': 'Box',
  'Serviettes hygiéniques': 'Box',
  'Couches': 'Box',
  'Vitamines': 'Pill',
  'Compléments': 'Pill',
  'Compléments alimentaires': 'Pill',
  'Protéines en poudre': 'Pill',
  'Pansements': 'Pill',
  'Thermomètre': 'Pill',
  'Gel hydroalcoolique': 'SprayCan',

  // ── Animaux ──
  'Croquettes chien': 'Dog',
  'Croquettes chat': 'Cat',
  'Croquettes': 'Dog',
  'Pâtée chien': 'Dog',
  'Pâtée chat': 'Cat',
  'Pâtée': 'Dog',
  'Friandises chien': 'Dog',
  'Friandises chat': 'Cat',
  'Litière chat': 'Cat',
  'Litière': 'Cat',
  'Sacs déjection': 'Dog',
  'Jouet chien': 'Dog',
  'Jouet chat': 'Cat',
  'Os': 'Dog',
  'Gamelle': 'Dog',
  'Brosse chien': 'Dog',
  'Brosse chat': 'Cat',
  'Shampoing chien': 'Dog',
  'Shampoing chat': 'Cat',
  'Anti-puces': 'Pill',
};

/** Get the Lucide icon component for a product by name */
export function getProductIcon(name: string): LucideIcon {
  const iconName = PRODUCT_ICONS[name];
  return iconName ? getIcon(iconName) : FALLBACK_ICON;
}

/** Get the icon for a product, falling back to its category icon if not found */
export function getProductOrCategoryIcon(name: string, category: string): LucideIcon {
  const iconName = PRODUCT_ICONS[name];
  if (iconName) return getIcon(iconName);
  return getCategoryIcon(category);
}
